@startuml


namespace GameManagers{
    class GameSceneManager
    class InGameManager
}

namespace uitls{
    class MoveOnSpline
}
namespace Enemys{
    
    EnemyManager -- MobEnemy
    EnemyManager -- BossEnemy
    
    interface IAttackable
    class EnemyManager
    
    class MobEnemy
    class BossEnemy
    BossEnemy ..|> IAttackable
    MobEnemy ..|> IAttackable
}

namespace PlayerRobots{
    PlayerRobotManager o-- PlayerAttackerComponent
    PlayerRobotManager o-- LockOn
    PlayerRobotManager o-- ButtonAnimationManager
    
    class PlayerRobotManager 
    class PlayerAttackerComponent
    class LockOn
    class ButtonAnimationManager
    class CollisionNotificatorToEnemy
}

GameManagers.GameSceneManager o- GameManagers.InGameMnager
PlayerRobots.CollisionNotificatorToEnemy -o  Enemys.EnemyManager
GameManagers.InGameManager o- PlayerRobots.PlayerRobotManager



@enduml